language: php

php:
  - 7.1

env:
  global:
    - SEND_COVERAGE=false
    - PHPSTAN=false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SEND_COVERAGE=true
    # phpstan
    - php: 7.1
      env: PHPSTAN=true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer validate

install:
  - composer install --no-interaction --prefer-dist --no-progress --profile

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - mkdir -p build/logs
  - if [[ "$PHPSTAN" = false && "$SEND_COVERAGE" = true ]]; then ./vendor/bin/php-cs-fixer fix --verbose --diff --dry-run; fi
  - if [[ "$PHPSTAN" = false && "$SEND_COVERAGE" = true ]]; then ./vendor/bin/phpunit -c phpunit.xml.dist --verbose --coverage-clover=coverage.xml; fi
  - if [[ "$PHPSTAN" = true && "$SEND_COVERAGE" = false ]]; then ./vendor/bin/phpstan analyse -c phpstan.neon -l 6 src; fi
  - if [[ "$PHPSTAN" = true && "$SEND_COVERAGE" = false ]]; then ./vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$PHPSTAN" = false && "$SEND_COVERAGE" = true ]]; then bash <(curl -s https://codecov.io/bash); fi